// МАССИВ ИНФОРМАЦИИ РЕГИОНОВ
var arrForModal = 
[[{"icoUrl":"bazBox","nameCategory":"Газовое оборудование","num":"120"},{"icoUrl":"emcostBox","nameCategory":"Емкостное оборудование","num":"44"},{"icoUrl":"blockBox","nameCategory":"Блочные котельные установки","num":"6"},{"icoUrl":"SAUBox","nameCategory":"САУ ТП","num":"13"},{"icoUrl":"BlockKIPiaBox","nameCategory":"Блоки КИПиА","num":"17"}],[{"icoUrl":"bazBox","nameCategory":"Газовое оборудование","num":"103"},{"icoUrl":"NeftBazBox","nameCategory":"Нефтяное оборудование","num":"3"},{"icoUrl":"emcostBox","nameCategory":"Емкостное оборудование","num":"4"},{"icoUrl":"blockBox","nameCategory":"Блочные котельные установки","num":"2"},{"icoUrl":"SAUBox","nameCategory":"САУ ТП","num":"64"},{"icoUrl":"BlockKIPiaBox","nameCategory":"Блоки КИПиА","num":"67"}],[{"icoUrl":"bazBox","nameCategory":"Газовое оборудование","num":"8"},{"icoUrl":"emcostBox","nameCategory":"Емкостное оборудование","num":"2"},{"icoUrl":"SAUBox","nameCategory":"САУ ТП","num":"1"},{"icoUrl":"BlockKIPiaBox","nameCategory":"Блоки КИПиА","num":"19"}],[{"icoUrl":"bazBox","nameCategory":"Газовое оборудование","num":"11"},{"icoUrl":"NeftBazBox","nameCategory":"Нефтяное оборудование","num":"1"},{"icoUrl":"emcostBox","nameCategory":"Емкостное оборудование","num":"33"},{"icoUrl":"SAUBox","nameCategory":"САУ ТП","num":"7"},{"icoUrl":"BlockKIPiaBox","nameCategory":"Блоки КИПиА","num":"7"}],[{"icoUrl":"bazBox","nameCategory":"Газовое оборудование","num":"34"},{"icoUrl":"emcostBox","nameCategory":"Емкостное оборудование","num":"7"},{"icoUrl":"blockBox","nameCategory":"Блочные котельные установки","num":"1"},{"icoUrl":"SAUBox","nameCategory":"САУ ТП","num":"23"},{"icoUrl":"BlockKIPiaBox","nameCategory":"Блоки КИПиА","num":"24"}],[{"icoUrl":"bazBox","nameCategory":"Газовое оборудование","num":"10"},{"icoUrl":"NeftBazBox","nameCategory":"Нефтяное оборудование","num":"1"},{"icoUrl":"blockBox","nameCategory":"Блочные котельные установки","num":"2"},{"icoUrl":"SAUBox","nameCategory":"САУ ТП","num":"7"},{"icoUrl":"BlockKIPiaBox","nameCategory":"Блоки КИПиА","num":"6"}],[{"icoUrl":"bazBox","nameCategory":"Газовое оборудование","num":"36"},{"icoUrl":"blockBox","nameCategory":"Блочные котельные установки","num":"3"},{"icoUrl":"SAUBox","nameCategory":"САУ ТП","num":"7"},{"icoUrl":"BlockKIPiaBox","nameCategory":"Блоки КИПиА","num":"7"}],[{"icoUrl":"bazBox","nameCategory":"Газовое оборудование","num":"28"},{"icoUrl":"NeftBazBox","nameCategory":"Нефтяное оборудование","num":"4"},{"icoUrl":"blockBox","nameCategory":"Блочные котельные установки","num":"2"},{"icoUrl":"SAUBox","nameCategory":"САУ ТП","num":"8"},{"icoUrl":"BlockKIPiaBox","nameCategory":"Блоки КИПиА","num":"10"}],[{"icoUrl":"bazBox","nameCategory":"Газовое оборудование","num":"15"},{"icoUrl":"emcostBox","nameCategory":"Емкостное оборудование","num":"5"},{"icoUrl":"blockBox","nameCategory":"Блочные котельные установки","num":"1"},{"icoUrl":"SAUBox","nameCategory":"САУ ТП","num":"13"},{"icoUrl":"BlockKIPiaBox","nameCategory":"Блоки КИПиА","num":"13"}]]



const arr = [
    {x: "3.5", y: "39", town: "Калининград", uri: "", class: "cityKaliningAD"},
    {x: "12", y: "43", town: "Санкт-Петербург", uri: "", class: "city"},
    {x: "23.5", y: "35.5", town: "Мурманск", uri: "", class: "classTextMapClient"},
    {x: "32.5", y: "45.5", town: "Воркута", uri: "", class: "classTextMapClient"},
    {x: "15", y: "52", town: "Ярославль", uri: "", class: "classTextMapClient"},
    {x: "10", y: "52.5", town: "Москва", uri: "", class: "classTextMapClient"},
    {x: "10", y: "59", town: "Тула", uri: "", class: "classTextMapClient"},
    {x: "1.3", y: "62.7", town: "Севастополь", uri: "", class: "classSevastopal"},
    {x: "8.5", y: "65", town: "Волгоград", uri: "", class: "classTextMapClient"},
    {x: "8.9", y: "68.5", town: "Краснодар", uri: "", class: "classTextMapClient"},
    {x: "10", y: "73", town: "Астрахань", uri: "", class: "classTextMapClient"},
    {x: "7.5", y: "75.5", town: "Сочи", uri: "", class: "classTextMapClient"},
    {x: "8", y: "78.5", town: "Махачкала", uri: "", class: "MaxackalaClass"},
    {x: "13", y: "81.5", town: "Актау", uri: "", class: "colorBlueBox"},
    {x: "15.5", y: "70", town: "Уральск", uri: "", class: "colorBlueBox"},
    {x: "21", y: "75.5", town: "Актобе", uri: "", class: "colorBlueBox"},
    {x: "30", y: "73.5", town: "Нур-Султан", uri: "", class: "colorBlueBox"},
    {x: "26", y: "84", town: "Кызылорда", uri: "", class: "colorBlueBox"},
    {x: "28", y: "86.5", town: "Туркестан", uri: "", class: "colorBlueBox"},
    {x: "31", y: "89", town: "Шымкент", uri: "", class: "colorBlueBox"},
    {x: "36", y: "89", town: "Алматы", uri: "", class: "colorBlueBox"},
    {x: "15.5", y: "65", town: "Саратов", uri: "", class: "classTextMapClient"},
    {x: "16.5", y: "61.5", town: "Самара", uri: "", class: "classTextMapClient"},
    {x: "20", y: "59.5", town: "Казань", uri: "", class: "classTextMapClient"},
    {x: "24.5", y: "61", town: "Уфа", uri: "", class: "classTextMapClient"},
    {x: "16", y: "57", town: "Нижний Новгород", uri: "", class: "classTextMapClient"},
    {x: "26", y: "56", town: "Пермь", uri: "", class: "classTextMapClient"},
    {x: "27.5", y: "63.5", town: "Екатеринбург", uri: "", class: "classTextMapClient"},
    {x: "37.5", y: "60.5", town: "Тюмень", uri: "", class: "classTextMapClient"},
    {x: "41", y: "51.5", town: "Пурпе", uri: "", class: "classTextMapClient"},
    {x: "36.5", y: "70", town: "Омск", uri: "", class: "classTextMapClient"},
    {x: "41", y: "75", town: "Новосибирск", uri: "", class: "classTextMapClient"},
    {x: "45", y: "69", town: "Томск", uri: "", class: "classTextMapClient"},
    {x: "53", y: "72.5", town: "Красноярск", uri: "", class: "classTextMapClient"},
    {x: "59", y: "75.5", town: "Иркутск", uri: "", class: "classTextMapClient"},
    {x: "70", y: "74", town: "Чита", uri: "", class: "classTextMapClient"},
    {x: "48.5", y: "41", town: "Норильск", uri: "", class: "classTextMapClient"},
    {x: "88", y: "76.5", town: "Владивосток", uri: "", class: "vladic"},
    {x: "81", y: "68.5", town: "Благовещенск", uri: "", class: "classTextMapClient"},
    {x: "86", y: "65.5", town: "Хабаровск", uri: "", class: "classTextMapClient"},
    {x: "91", y: "59", town: "Южно-Сахалинск", uri: "", class: "sahalinClass"},
    {x: "71", y: "53", town: "Якутск", uri: "", class: "classTextMapClient"},
    {x: "72.5", y: "40", town: "Вилюйск", uri: "", class: "classTextMapClient"},
    {x: "83", y: "39", town: "Магадан", uri: "", class: "classTextMapClient"},
    {x: "92", y: "38", town: "Елизово", uri: "", class: "classTextMapClient"},
    {x: "86.5", y: "18.5", town: "Анадырь", uri: "", class: "classTextMapClient"}
    ]